### ISSUE TITLE
Demo please !

### ISSUE THREAD

**Issue by sparta3407** [pwntester/ysoserial.net#1]

**Comment by pwntester** [comment]
Will add a link to the talk demos when these are published (either by BH, Defcon or OWASP)

**Comment by JarLob** [comment]
@sparta3407 There is --test argument if you want to see payload demo.

**Comment by pwntester** [comment]
Also, just added a recording of the talk to README.md. It includes 3 demos for:
- JSON.NET (Breeze)
- BinaryFormatter (Nancy)
- XmlSerializer (DotNetNuke)
