### ISSUE TITLE
there is no any file present ysoserial.exe 

### ISSUE THREAD

**Issue by sushantdhopat19** [pwntester/ysoserial.net#101]
there is no file present `ysoserial.exe` on this tool i didnt get this file any where how can i run this tool

**Comment by halfluke** [comment]
It's on the Releases section of the main page, on the right, in a zip file. And there is no need to repeat your question under non-related issues

**Comment by sushantdhopat19** [comment]
After i download the zip going to this path `/ysoserial.net-master/ysoserial/bin/Release` and run `./ysoserial.exe -h`  this cmd i got this error `zsh: exec format error: ./ysoserial.exe`

**Comment by sushantdhopat19** [comment]
after downloading zip file on the window there i got `ysoserial.net` in the `ysoserial.net-master` in the linux i didnt get any thing like this 

in the window

![window cmd](https://user-images.githubusercontent.com/57283755/103549097-d80da580-4ecc-11eb-956b-0db9649216d8.png)

**Comment by pwntester** [comment]
this is a windows only executable sorry
