### ISSUE TITLE
033102051731: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by xcyber02** [pwntester/ysoserial.net#116]
i got this error message

****033102051731: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Service.Common.Login(String plainText)****

my commad
ysoserial.exe -f JavaScriptSerializer -g ObjectDataProvider -o raw -c "calc" -t
ysoserial.exe -f Json.Net -g ObjectDataProvider -o raw -c "calc" -t

and the client send this param to server
{"username":"test","password":"test","deviceId":"698c7e","key":"716cbce586913b54"}
key was the aes key for encryption

am i  missing something? or what's wrong with this method? i'm a beginner on asp and json deserialize

thanks

**Comment by irsdl** [comment]
This error from the web application has nothing to do with the deserialization payload from ysoserial.net. It only shows the key was invalid. Please read the references within the readme section to get more info on how deserialization attacks (especially in JSON) work and to see some examples.
