### ISSUE TITLE
Update Outdated Dependencies

### ISSUE THREAD

**Issue by gwillcox-r7** [pwntester/ysoserial.net#121]
Many dependencies of this project are now long longer supported, have been removed from NuGet for the version specified, or contain security issues in the version used. It would likely be a good idea to go a run through of all of the dependencies and update the project to use more modern versions where applicable or find suitable replacements where the project is no longer maintained.

**Comment by irsdl** [comment]
Whilst a few of the libraries can get updated, this project uses some vulnerable libraries intentionally to generate and test payloads for vulnerable applications. Please refer to the readme file to see what this project is all about and why most of the libraries should be kept as is.

I can compile the project without any issues using my VS2022 at the moment `Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.3.0`. Perhaps they have fixed the issue in their latest version.
