### ISSUE TITLE
fix artifact and document how to compile

### ISSUE THREAD

**Issue by gogo2464** [pwntester/ysoserial.net#152]
I got a bug on the latest release. So:

I download latest artifacts from https://github.com/pwntester/ysoserial.net/actions/runs/5154471291

Then I realized these one had bugs 

```powershell
.\ysoserial.exe -f BinaryFormatter -g TypeConfuseDelegateMono -o raw -c "calc"

Exception non gérée : System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à ysoserial.Generators.TypeConfuseDelegateMonoGenerator.TypeConfuseDelegateGadget(InputArgs inputArgs) dans D:\a\ysoserial.net\ysoserial.net\ysoserial\Generators\TypeConfuseDelegateMonoGenerator.cs:ligne 83
   à ysoserial.Generators.TypeConfuseDelegateMonoGenerator.Generate(String formatter, InputArgs inputArgs) dans D:\a\ysoserial.net\ysoserial.net\ysoserial\Generators\TypeConfuseDelegateMonoGenerator.cs:ligne 43
   à ysoserial.Generators.GenericGenerator.GenerateWithInit(String formatter, InputArgs inputArgs) dans D:\a\ysoserial.net\ysoserial.net\ysoserial\Generators\GenericGenerator.cs:ligne 75
   à ysoserial.Program.Main(String[] args) dans D:\a\ysoserial.net\ysoserial.net\ysoserial\Program.cs:ligne 302
```

So I tried to compile from source and I saw no documentation.

Could you first fix the artifact and then provide compilation documentation please?

**Comment by gogo2464** [comment]
@irsdl I mention you because you are the author of https://github.com/pwntester/ysoserial.net/pull/127/files

**Comment by irsdl** [comment]
Thanks, I need to look into this when I get the chance probably in the next coming month. I have a feeling you will need to run ysoserial.net using mono to get this gadget working but I can't fully remember it. Please let me know if you have tried that and it didn't work.

**Comment by gogo2464** [comment]
I tried with a real target... IT did not worked but I may have done a mistake.

**Comment by gogo2464** [comment]
@irsdl do you mean mono installed?

**Comment by meme-lord** [comment]
I was able to use these gadgets on Linux with mono. You run it like this:
```sh
mono ysoserial.exe -f BinaryFormatter -g TypeConfuseDelegateMono -o raw -c "calc"
```
I assume mono works the same way on Windows.
