### ISSUE TITLE
Default output format - Release 1.35

### ISSUE THREAD

**Issue by 0xjamesli** [pwntester/ysoserial.net#155]
It seems the default output format is base64, not raw.

![image](https://github.com/pwntester/ysoserial.net/assets/35205556/39755b46-d641-4c8a-a387-b1a0b613d76f)

![image](https://github.com/pwntester/ysoserial.net/assets/35205556/def91925-a8d6-416a-b999-7b3cd558304f)

**Comment by irsdl** [comment]
This should be resolved now. The output type changes by which formatter is being selected.
