### ISSUE TITLE
Bug Report: Regex in DataContractSerializer_Marshal_2_MainType Function

### ISSUE THREAD

**Issue by NtAlexio2** [pwntester/ysoserial.net#158]
The function `DataContractSerializer_Marshal_2_MainType` within the `SerializersHelper.cs` file, accessible [here](https://github.com/pwntester/ysoserial.net/blob/master/ysoserial/Helpers/SerializersHelper.cs#L352), contains a bug resulting in invalid data serialization for specific gadgets utilizing the NetDataContractSerializer formatter. The affected gadgets include:

1. [RolePrincipal](https://github.com/pwntester/ysoserial.net/blob/master/ysoserial/Generators/RolePrincipalGenerator.cs#L130)
2. [AxHostState](https://github.com/pwntester/ysoserial.net/blob/master/ysoserial/Generators/AxHostStateGenerator.cs#L69)
3. [TextFormattingRunProperties](https://github.com/pwntester/ysoserial.net/blob/master/ysoserial/Generators/TextFormattingRunPropertiesGenerator.cs#L158)

When these gadgets are utilized with the `NetDataContractSerializer` formatter, they produce invalid serialized objects.

**Resolution**:
A fast workaround for this issue involves commenting out the NetDataContractSerializer_Marshal_2_MainType reference in each affected gadget and using the serialized object directly. For instance, in the first case, the line:
```
string payload = SerializersHelper.NetDataContractSerializer_Marshal_2_MainType(utfString);
```
with
```
string payload = utfString;
```

Thank you for maintaining this exceptional project. Your efforts are greatly appreciated!

**Comment by irsdl** [comment]
Using the `utfString` without cleaning it will produce wrong data especially when we are creating it from an irrelevant class. Could you please provide me with an example of wrong data being produced?

If run `ysoserial.exe -g TextFormattingRunProperties -f NetDataContractSerializer -c calc -t` it works straight away.

**Comment by irsdl** [comment]
Thanks for more information, it seems the `--minify` argument indeed breaks NetDataContractSerializer. Here is another broken one:
```
ysoserial.exe -g TextFormattingRunProperties -f NetDataContractSerializer -c calc -t --minify
```

This happens when we have no test unit! Whoever has implemented the `--minify` flag is at fault here (point at myself)! 
I will have a look soon to see how I can resolve this. For now, I recommend using generic XML minifiers instead of the one implemented by me in this project.

**Comment by irsdl** [comment]
This should be fixed now.
