### ISSUE TITLE
make artifact life time longer

### ISSUE THREAD

**Issue by gogo2464** [pwntester/ysoserial.net#163]
Hello,

I can not download the artifact at: https://github.com/pwntester/ysoserial.net/pull/156/checks

Can you prolonge life time please?

Best regards.

**Comment by irsdl** [comment]
@gogo2464 you can always fork it and run the actions that way. On the other hand, perhaps we can push a new version on each release automatically there @pwntester?

**Comment by irsdl** [comment]
@gogo2464 I just checked and it seems the latest release https://github.com/pwntester/ysoserial.net/releases/tag/v1.36 is based on the latest code. So you should be able to download the latest version from there.

**Comment by gogo2464** [comment]
thanks I will check

**Comment by gogo2464** [comment]
@irsdl I checked and from the latest version I ensured and yes ysoserial -f BinaryFormatter -g TypeConfuseDelegateMono -c calc.exe still does not work.

**Comment by irsdl** [comment]
@gogo2464 I think I know your issue now, in order to make the payload, you need to run ysoserial using mono:
```
"C:\Program Files (x86)\Mono\bin\mono.exe" ysoserial.exe -g TypeConfuseDelegateMono -f binaryformatter -c calc -t
```
Download it from https://www.mono-project.com/download/stable/#download-win

**Comment by gogo2464** [comment]
Let me try!

**Comment by gogo2464** [comment]
IT WORKS !!! THANKS! Let's document it!
