### ISSUE TITLE
How to generate a payload for the AES validation method ViewState?

### ISSUE THREAD

**Issue by wpf97** [pwntester/ysoserial.net#166]
Hello!
Test using HMACSHA256 validation method to generate ViewState and successfully execute the command.
![1](https://github.com/pwntester/ysoserial.net/assets/22408189/0a3a8d7b-98c3-483f-a207-c5cba6da49fa)
Test AES validation method to generate ViewState, command execution failed.
![2](https://github.com/pwntester/ysoserial.net/assets/22408189/ca0b5f6b-4f89-4af5-98a4-1c5ab0a861e2)
The information is as follows
![3](https://github.com/pwntester/ysoserial.net/assets/22408189/a4db7be2-7fb6-403f-9f55-2241438eb41a)
Looking forward to your reply

**Comment by irsdl** [comment]
@wpf97 Please review the final version as it should have resolved the issue. I close this for now.
