### ISSUE TITLE
Any gadget for DataContractJsonSerializer ?

### ISSUE THREAD

**Issue by gerardocanedo** [pwntester/ysoserial.net#17]
Hi,

I'm looking for a gadget that can be used for the DataContractJsonSerializer Serializer.
If there is any, I can test it and include it into the tool.

Thanks,
Gerardo

**Comment by pwntester** [comment]
Closing

**Comment by CCob** [comment]
Did anyone get anywhere with this?  I'm struggling to convert an XML version of DataContractSerializer to JSON.

**Comment by RealLinkers** [comment]
Would be cool to get an easy to generate gadget ready for DataContractJsonSerializer

**Comment by CCob** [comment]
I looked a bit further into this, might not be possible with .NET one since it doesn't support object references like XML does.

**Comment by RealLinkers** [comment]
I think you need to use the ExpandedWrapper class in order to wrap the payload like is done for the DataContractSerializer.
