### ISSUE TITLE
Changing the command argument case in DotNetNukePlugin

### ISSUE THREAD

**Issue by irsdl** [pwntester/ysoserial.net#21]
I think the command argument (`"C|command="`) should be in lowercase (`"c|command="`) for `/ysoserial/Plugins/DotNetNukePlugin.cs` to match the rest of the tool.

**Comment by pwntester** [comment]
I was using capital letters for plugin options, just in case they share an option with the main tool as it is the case in this plugin. Probably should make this clearer in a wiki page about plugins

**Comment by pwntester** [comment]
I can see you used lower case for your plugin options and since plugins should not be used along with normal ysoserial.net options, there is probably no problem overriding them. So will fix the DNN one and make it lower case

**Comment by irsdl** [comment]
I thought if options are the same (like command or test) they can just use the same thing.

**Comment by pwntester** [comment]
Can you make yours lowercase as well?

**Comment by irsdl** [comment]
For the ones shared with the main project (such as `command` or `test` ) mine should already use lowercase. I have used capital letters for the ones different than the main project to reduce confusion. For example if we use lowercase `f` for `file` when it is `formatter` for the main project, we may just cause confusions? I like the fact that we could still use the main application command just in case they are needed in the future (imagine if a plugin really wants to make use of the formatter or output needs to be base64 encoded).

Also `-F` in the Clipboard plugin is used for formatting but that's different than a formatter.

With all that, if you still want to make everything lowercase, please let me know.

**Comment by irsdl** [comment]
I am closing this for now
