### ISSUE TITLE
Is there any gadget for .NET Core?

### ISSUE THREAD

**Issue by JarLob** [pwntester/ysoserial.net#25]
Quickly tried to make a sample vulnerable .NET Core 2.1 app. It looks like none of the gadget works on .net core :( but maybe I missed something.

**Comment by pwntester** [comment]
None of the existing gadgets work on .NET Core. You may want to try the new gadget checked in by @o-mirosh it may work on Windows since it depends on PowerShell dll

**Comment by heikar** [comment]
Any news for .NET Core?

**Comment by pwntester** [comment]
nope, if anyone has time to look for them and find interesting gadgets, please send PR, for now will close this issue
