### ISSUE TITLE
Gadgets for Mono?

### ISSUE THREAD

**Issue by gsuberland** [pwntester/ysoserial.net#28]
Are there any gadgets out there for Mono? I'd be willing to implement them but I can't find any research into attacking deserialization on Mono, or Unity for that matter. Target platform is Windows.

**Comment by pwntester** [comment]
Im afraid there are no mono gadgets at the moment. They are very welcome :)

**Comment by denandz** [comment]
Just in case someone stumbles across this issue like I did, the solution is to tweak `TypeConfuseDelegate` to work with mono (and Unity!). I've detailed the patch here: https://gist.github.com/denandz/aa2b7bd145c95b430cfc0386a9e6ce40 

@pwntester - I'll wrap this up into a new gadget and send you through a pull request when I get some spare time

**Comment by pwntester** [comment]
Awesome, thanks

**Comment by halfluke** [comment]
Hi.

Any idea why the typeconfusedelegatemono doesn't work for me?

I built the supersimple example from https://www.monodevelop.com/documentation/creating-aspnet-projects/ and I run it in xsp4, but the viewstate - which should be MAC enabled but not encrypted, .net 4.0 version, looks weird and the payload generated by ysoserial.net - which is much longer - does not work. I'm using a specific validationkey in web.config for testing.

%2FwEMDAwQAgAADgEMBQMMEAIAAA4BDAUBDBACDA8BAQRUZXh0AQ5Zb3UgY2xpY2tlZCBtZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALvN0281sXomxFcIhy33ycX5EfZiafqaB78GIBHdjmVX

**Comment by gogo2464** [comment]
you can close https://github.com/pwntester/ysoserial.net/issues/86

**Comment by gogo2464** [comment]
Actually no. Your gadget is just not working anymore.

**Comment by irsdl** [comment]
The gadget had a bug which I am going to fix in the next release to work with the latest version of Mono.

**Comment by gogo2464** [comment]
@irsdl thanks! did you test it in 2024 please?

**Comment by irsdl** [comment]
@gogo2464 I haven't tested this gadget in 2024 but it used to work. I don't think they have changed Mono, have they?

**Comment by irsdl** [comment]
If there is anything wrong with it, please open a new issue with more details.

**Comment by gogo2464** [comment]
I will test on a real target. it will take a lot of time.
