### ISSUE TITLE
Precompiled or Build Dependency guide

### ISSUE THREAD

**Issue by subrosaassociates** [pwntester/ysoserial.net#33]
Precompiled or Build Dependency guide

Hey all, 2 questions really

is there a binary ?

I've installed visual studio 2019, while I could list the dependencies it's erroring on during build phase I have to ask, is there a dependency/build guide that I've ignored/overlooked ?

**Comment by h3xstream** [comment]
`Build` > `Rebuild Solution` should do the trick

Dependencies are managed with nuget.
You can force the download the dependencies by right-clicking on the solution and choosing the "Restore Nuget Packages"

Something settings are configurable at `Tools` > `Options` > `NuGet Package Manager`.

**Comment by pwntester** [comment]
For the first question, yep, check the releases tab although is not  up to date but should contains all gadgets.
