### ISSUE TITLE
Creation of a dockerfile

### ISSUE THREAD

**Issue by dduzgun** [pwntester/ysoserial.net#47]
### Description
To make ysoserial **accessible in multiple platforms** (mac, linux, windows), containerizing the code is a good solution. Once it's here, adding it on docker registry can ease the installation processes. The user would only have to pull the image and run it regardless of what is his OS.

### Reference
https://puppet.com/docs/pipelines-for-apps/enterprise/docker-c-sharp.html
https://docs.docker.com/engine/examples/dotnetcore/

**Comment by pwntester** [comment]
This project is not compatible with dotnet code and niether are the supported gadgets. So unfortunately we cannot dockerize it
