### ISSUE TITLE
Gives Permission Denied error while trying to run the ysoserial executable

### ISSUE THREAD

**Issue by hackerpain** [pwntester/ysoserial.net#59]
I am facing an issue with the downloaded pre-compiled executable (1.32 latest release).
When I try to run the executable, it gives a permission denied error like -

```-bash: ./ysoserial.exe: Permission denied```

I am running it through Cygwin.

**Comment by hackerpain** [comment]
Can anyone explain why this is happening?

**Comment by MagicZer0** [comment]
It's obviously that cause the privileges, run as administrator.

**Comment by hackerpain** [comment]
> It's obviously that cause the privileges, run as administrator.

I did that back then but still it gave out the same error. I am on windows and using cygwin (running with admin privs)

**Comment by hackerpain** [comment]
@irsdl @pwntester plz help!

**Comment by w0ot-net** [comment]
@hackerpain are you running some kind of AV that is identifying ysoserial as a 1337 hak tool?

**Comment by hackerpain** [comment]
I uninstalled Norton @w0ot-net, also checked Defender which isn't blocking it :/

**Comment by irsdl** [comment]
have you run this on Windows? Please try the latest version and more debugging data would be useful

**Comment by hackerpain** [comment]
Yes @irsdl run on Windows.

Even after running PS with admin priv, was giving error, but when I ```chmod +x``` on cygwin, it worked magically...

Is it due to how my Windows is configured?

cheers

**Comment by irsdl** [comment]
I am not sure what the problem was for you tbh. I don't use cygwin to run it. Powershell and normal command prompt both works fine for me without any errors. I don't use Win Defender though (I have another AV)

**Comment by irsdl** [comment]
Closed to inactivity - please re-open when you have more details if the issue is still there
