### ISSUE TITLE
Integrate into Zaproxy?

### ISSUE THREAD

**Issue by omerlh** [pwntester/ysoserial.net#6]
This tool could be really awesome if it will be integrated into Zap - using it to attack/tests web app will be a lot easier. I've opened an issue (zaproxy/zaproxy#4112) - so feel free to join the discussion...

**Comment by pwntester** [comment]
Ive written a passive scanner for burp that I will publish soon. Once I publish it, it should be easy to port to ZAP. As for active scanning, ysoserial can produce payloads that would cause a delay in the response so they can be detected by ZAP/Burp, but I have no plans right now to implement that.

**Comment by irsdl** [comment]
We have this plugin for Burp (active and passive): https://github.com/nccgroup/freddy/ - Perhaps you can also port it into ZAP but I don't know whether ZAP has similar capability of Burp Collaborator for the active scans.
