### ISSUE TITLE
Cannot build execute file

### ISSUE THREAD

**Issue by hobaonghia** [pwntester/ysoserial.net#71]
I tried to build the ysoserial solution but it throwing the errors:

> The type or namespace name 'NDesk' could not be found (are you missing a using directive or an assembly reference?)	
> The type or namespace name 'OptionSet' could not be found (are you missing a using directive or an assembly reference?)	

I already installed .Net Framework 4.5.2, tried to rebuild the solution but did not help, what could I miss? Thanks a lot

**Comment by irsdl** [comment]
Perhaps use the latest .NET version - otherwise install an appropriate NDesk version from NuGet

**Comment by irsdl** [comment]
No update in a while
