### ISSUE TITLE
Cannot compile TypeConfuseDelegate gadget

### ISSUE THREAD

**Issue by sunlinerolex** [pwntester/ysoserial.net#72]
https://github.com/pwntester/ysoserial.net/blob/32ec44f93b9bc6a5f8608a6b5beee5a4def019be/ysoserial/Generators/TypeConfuseDelegateGenerator.cs#L41
https://github.com/pwntester/ysoserial.net/blob/32ec44f93b9bc6a5f8608a6b5beee5a4def019be/ysoserial/Generators/TypeConfuseDelegateGenerator.cs#L42

I've noticed that the class here is not referenced inside the VS Project. I tried to import and when compiling it give me errors:

 error CS0117: 'Comparer<string>' does not contain a definition for 'Create'
 error CS0246: The type or namespace name 'SortedSet<>' could not be found (are you missing a using directive or an assembly reference?)

I've noticed that the class SortedSet<T> is not present into .NET 2.0 and neither does Comparer.Create

Since this gadget should be smaller than ActivitySurrogateSelector, I'd like to compile and use it.
Is this class left outside the project on purpose? Is there a way to compile it and use on .NET 2.0 targets?

**Comment by irsdl** [comment]
This gadget cannot work with .NET Framework 2.0 as SortedSet was introduced after .NET Framework version 4.0. (see https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1)
