### ISSUE TITLE
XMLMinifier removing needed variables

### ISSUE THREAD

**Issue by stevenseeley** [pwntester/ysoserial.net#77]
The [XLST](https://github.com/pwntester/ysoserial.net/blob/master/ysoserial/Helpers/XMLMinifier.cs#L266) in the XMLMinifier is removing needed variables for the datacontractserializer formatter when using the  [WindowsPrinciple](https://github.com/pwntester/ysoserial.net/blob/master/ysoserial/Generators/WindowsPrincipalGenerator.cs#L127) gadget.

This is a reminder for @irsdl to patch the XSLT to give the option of removing the variables or not and/or only remove the variables if not in use.

**Comment by irsdl** [comment]
The new PR should resolve this issue. Another workaround is to use all the XML namespace declarations to the main XML tag rather than keeping them in the nodes.
