### ISSUE TITLE
Help on how to build.

### ISSUE THREAD

**Issue by abrahack** [pwntester/ysoserial.net#79]
Please am trying to build the v2 branch for an old asp.net server i came across.
Please help with guide on how to build.

**Comment by irsdl** [comment]
You need to use Windows and build it against .net version 3.5. What's the error you are having?

**Comment by abrahack** [comment]
how am i going to specify the version to version 3.5 am using VS 2019.
Am here is the error message.
[message.txt](https://github.com/pwntester/ysoserial.net/files/4746030/message.txt)

**Comment by irsdl** [comment]
Do you have .NET framework 2.0 and 3.5 both installed on your box and still getting this error? It seems it cannot find .NET 2 based on the errors

**Comment by abrahack** [comment]
i do .

**Comment by abrahack** [comment]
and you said i should specify the version how ?

**Comment by irsdl** [comment]
I have updated the repo to reflect this. If you have any problems, please re-open this.
