### ISSUE TITLE
'-s' parameter doesn't work while using -p 'ViewState'

### ISSUE THREAD

**Issue by kejaly** [pwntester/ysoserial.net#83]
hi , I get a problem where I use ' -s ' with -p 'ViewState' together , 
![image](https://user-images.githubusercontent.com/46043605/87226876-4dd6ff80-c3c9-11ea-83a5-377f62442b80.png)

and if i can't use '-s' while using "-p 'viewState'" ,how can i  deal with the special character , my cmd command is :

![image](https://user-images.githubusercontent.com/46043605/87226964-013ff400-c3ca-11ea-8bae-e263dcdc6617.png)

**Comment by irsdl** [comment]
stdin argument is only used for gadgets not plugins. Use `-c "powershell.exe -encodedCommand $encodedCommand"` and encode your inputs. Example here: https://www.nccgroup.com/uk/about-us/newsroom-and-events/blogs/2018/august/aspnet-resource-files-resx-and-deserialisation-issues/
